aider: Fix import statement in ptycho/xpp.py to import scale_nphotons from .datasets.
# Aider chat conversation:

USER: I ran this command:

 pytest

And got this output:

============================= test session starts ==============================
platform linux -- Python 3.9.13, pytest-7.4.3, pluggy-1.3.0
rootdir: /home/ollie/Documents/scratch/ptycho
plugins: anyio-3.5.0, typeguard-2.13.3
collected 3 items

tests/test_tf_helper.py ..                                               [ 66%]
tests/test_xpp.py F                                                      [100%]

=================================== FAILURES ===================================
____________________ test_load_function_with_synthetic_data ____________________

    def test_load_function_with_synthetic_data():
        # Generate synthetic data similar to the expected experimental format
        diffraction_patterns = np.random.rand(2, 1000, 64, 64)
        scan_points = np.random.rand(2, 1000, 2)
        np.savez('synthetic_data.npz', diffraction=diffraction_patterns, scan_points=scan_points)

        # Load the synthetic data using the load function with the correct argument
>       data = load('test')  # Assuming you want to test with 'test' data

tests/test_xpp.py:12:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

which = 'test', kwargs = {}
global_offsets = array([[[[63.2646484 ],
         [57.54578915]]],

       [[[63.42999213],
         [58.17075989]]],

       [[[62.9...0.5393308 ]]],

       [[[62.9122122 ],
         [39.38610202]]],

       [[[61.46296625],
         [39.8275259 ]]]])
X = array([[[[0.        , 0.        , 0.        , 0.        ],
         [0.        , 0.        , 0.        , 0.        ],
...        [0.        , 0.        , 0.        , 0.        ],
         [0.        , 0.        , 0.        , 0.        ]]]])
coords_nominal = array([[[[ 1.62183805, -0.64688545, -0.26744538, -0.70750723],
         [ 0.0848721 , -1.14667661, -0.34404734,  1.405...[ 0.90182836, -0.03623251,  1.97163891, -2.83723476],
         [ 0.80919809, -1.64598407,  2.12226339, -1.28547741]]]])
coords_true = array([[[[ 1.62183805, -0.64688545, -0.26744538, -0.70750723],
         [ 0.0848721 , -1.14667661, -0.34404734,  1.405...[ 0.90182836, -0.03623251,  1.97163891, -2.83723476],
         [ 0.80919809, -1.64598407,  2.12226339, -1.28547741]]]])

    def load(which, **kwargs):
        global_offsets = split_tensor(dset[key_coords_offsets], which)
        X, coords_nominal, coords_true = get_splits(which, **kwargs)

>       norm_Y_I = datasets.scale_nphotons(X)
E       AttributeError: module 'ptycho.datasets' has no attribute 'scale_nphotons'

../../../anaconda3/envs/tf/lib/python3.9/site-packages/ptychoPINN-0.0.0-py3.9.egg/ptycho/xpp.py:121: AttributeError
=============================== warnings summary ===============================
../../../anaconda3/envs/tf/lib/python3.9/site-packages/tensorflow/python/framework/dtypes.py:246
  /home/ollie/anaconda3/envs/tf/lib/python3.9/site-packages/tensorflow/python/framework/dtypes.py:246: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
    np.bool8: (False, True),

../../../anaconda3/envs/tf/lib/python3.9/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:326
  /home/ollie/anaconda3/envs/tf/lib/python3.9/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:326: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
    np.bool8: (False, True),

../../../anaconda3/envs/tf/lib/python3.9/site-packages/tensorflow_probability/python/__init__.py:57
  /home/ollie/anaconda3/envs/tf/lib/python3.9/site-packages/tensorflow_probability/python/__init__.py:57: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    if (distutils.version.LooseVersion(tf.__version__) <

../../../anaconda3/envs/tf/lib/python3.9/site-packages/tensorflow_probability/python/__init__.py:58
  /home/ollie/anaconda3/envs/tf/lib/python3.9/site-packages/tensorflow_probability/python/__init__.py:58: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    distutils.version.LooseVersion(required_tensorflow_version)):

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED tests/test_xpp.py::test_load_function_with_synthetic_data - AttributeE...
=================== 1 failed, 2 passed, 4 warnings in 4.31s ====================

ASSISTANT: The error message indicates that the `load` function in `ptycho/xpp.py` is trying to call `scale_nphotons` from `ptycho.datasets`, but it cannot find this attribute. This suggests that either the import statement is incorrect or the `scale_nphotons` function is not available in the `ptycho.datasets` module.

Since we have access to `ptycho/datasets.py`, we can confirm that the `scale_nphotons` function is indeed defined in that module. Therefore, the issue is likely with the import statement in `ptycho/xpp.py`.

Let's correct the import statement in `ptycho/xpp.py`:

ptycho/xpp.py
```python
<<<<<<< SEARCH
from ptycho.datasets import scale_nphotons
=======
from .datasets import scale_nphotons
>>>>>>> REPLACE
```

Please apply this change and run the tests again to see if the issue is resolved.